[build]
  command = "pnpm run build"
  publish = "dist/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { NOT = [{Query = ["_next/static/*", "*.png", "*.jpg", "*.jpeg", "*.gif", "*.css", "*.js", "*.svg"]}] }
